import type { NextPage } from "next";
import Head from "next/head";
import { useRecoilValue } from "recoil";
import Guests from "../components/Guests/Guests";
import Menu from "../components/Menu/Menu";
import { step as atomStep } from "../stores/steps";
import styles from "../styles/Home.module.scss";
import NavigationModule from "../components/Navigation/Navigation";
import { useQuery } from "react-query";
import fetchRestaurantData from "../utils/api/fetchRestaurantData";
import Calendar from "../components/Calendar/Calendar";
import Confirmation from "../components/Confirmation/Confirmation";

const restaurantId = "62c1a011e95e96a91dbfd023";

const Home: NextPage = () => {
  const step = useRecoilValue(atomStep);

  const { data } = useQuery("restaurants", () =>
    fetchRestaurantData(restaurantId)
  );

  return (
    <div className={styles.container}>
      <Head>
        <title>Create Next App</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <NavigationModule />
      {step === "guests" && <Guests />}
      {step === "menu" && <Menu restaurantMenu={data?.menu} />}
      {step === "date" && <Calendar />}
      {data && (step === "conditions" || step === "final") && (
        <Confirmation restaurantName={data.name} />
      )}
    </div>
  );
};

export default Home;
