import type { NextPage } from "next";
import Head from "next/head";
import { useRecoilValue } from "recoil";
import Guests from "../components/Guests/Guests";
import Menu from "../components/Menu/Menu";
import { step as atomStep } from "../stores/steps";
import styles from "../styles/Home.module.scss";

const Home: NextPage = () => {
  const step = useRecoilValue(atomStep);
  console.log(step);

  return (
    <div className={styles.container}>
      <Head>
        <title>Create Next App</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      {step === "guests" && <Guests />}
      {step === "menu" && <Menu />}
    </div>
  );
};

export default Home;
